# Generated by rebar3_nix
let fetchOnly = { src, ... }: src;
in { builder ? fetchOnly, fetchHex, fetchgit, fetchFromGitHub, overrides ? (x: y: { }) }:
let
  self = packages // (overrides self packages);
  packages = with self; {
    ranch = builder {
      name = "ranch";
      version = "1.8.0";
      src = fetchHex {
        pkg = "ranch";
        version = "1.8.0";
        sha256 = "sha256-SfvP02gvqx9dEJNRthJXZ22hov2+KVkEF21eUhot3+U=";
      };
      beamDeps = [ ];
    };
    cowlib = builder {
      name = "cowlib";
      version = "2.11.0";
      src = fetchHex {
        pkg = "cowlib";
        version = "2.11.0";
        sha256 = "sha256-Kz6doLIcRWV1Gm1JAcING0zCXLt/1Q2R0qtt0oe8hqk=";
      };
      beamDeps = [ ];
    };
    jsx = builder {
      name = "jsx";
      version = "3.1.0";
      src = fetchHex {
        pkg = "jsx";
        version = "3.1.0";
        sha256 = "sha256-DFzI/cEbU8wlz2WsZwWtOeVOzFbRwi5K249aU/uUJ/M=";
      };
      beamDeps = [ ];
    };
    cowboy = builder {
      name = "cowboy";
      version = "2.9.0";
      src = fetchHex {
        pkg = "cowboy";
        version = "2.9.0";
        sha256 = "sha256-LHKfk0tOGqFJr/iC9XxjcsFTmaINVPZcjWe+9YMCG94=";
      };
      beamDeps = [ cowlib ranch ];
    };
  };
in self
